### ISSUE TITLE
Fonts not loading for SVGs correctly

### ISSUE THREAD

**Issue by JCGithu** [0atman/HumanMadeMark-com#1]
Hi Tris,

Apologies if this is intentional but I realised that the SVG version of the logo is in a different font on the site. I assume it is not embedding the font file and falling back to a default.

![Screenshot 2024-07-09 at 13 05 32](https://github.com/0atman/HumanMadeMark-com/assets/47216715/a27aba42-794d-4af9-b889-e5eb38f6dfcb)

Found the issue on Mac (Arc, Safari, Firefox) & Windows (Chrome, Firefox)
Works fine on Android (Chrome).

Really appreciate all your videos. Thanks.

**Comment by ajs1998** [comment]
I see the same thing

**Comment by 0atman** [comment]
HA that shows how much I know about graphics design!

I've converted the embedded font into paths in the SVG, this should now be platform-independent, and it now renders on my phone correctly. Thanks!
