### ISSUE TITLE
Automatic dark-mode for SVG

### ISSUE THREAD

**Issue by Jak2k** [0atman/HumanMadeMark-com#2]
You could embed CSS into the SVG to make it adapt to the color scheme. Your could also use the `Canvas` and `CanvasText` color to use system's colors.

**Comment by 0atman** [comment]
ooh cool idea, I'll get to this asap. Could you show me a screenshot of the problem?

**Comment by Jak2k** [comment]
> Could you show me a screenshot of the problem?

I haven't embedded it yet, but my website uses the system's theme and I don't want to write JS to dynamically load the correct image.

`Canvas` is just the user agent's default background & `CanvasText` the default text color. Using these colors will automatically make the image match the browser's color scheme.

Using a media query, you could stick to black & white, but still adapt to the theme.

**Comment by 0atman** [comment]
Ah! Apologies, I was thinking of my own site, but YES making it responsive on everyone's site is genius! I didn't even consider this option. I'll keep this issue open while I figure this out. 

(I'd be very grateful for a PR if you or anyone who reads this would be able to help out!)

**Comment by 0atman** [comment]
Apologies, closed accidentally while merging related PR.

**Comment by norwd** [comment]
I've added two new versions of the logo in #10, [automatic-logo-square.svg] and [automatic-logo.svg], which will react to the system settings. I didn't want to break backwards compatibility, so I haven't modified any of the existing images.

[automatic-logo-square.svg]: https://raw.githubusercontent.com/0atman/HumanMadeMark-com/b1bc793d7085ed4532349a4125a5d3d171f6c568/docs/automatic-logo-square.svg

[automatic-logo.svg]: https://raw.githubusercontent.com/0atman/HumanMadeMark-com/b1bc793d7085ed4532349a4125a5d3d171f6c568/docs/automatic-logo.svg

edit: fix the links to the images, I borked the markdown the first time

**Comment by 0atman** [comment]
fixed by @norwd in #10 - thanks!
