### ISSUE TITLE
too much tracking

### ISSUE THREAD

**Issue by goldenratio** [0atman/HumanMadeMark-com#3]
maybe, make the youtube video click to load.

![image](https://github.com/0atman/HumanMadeMark-com/assets/3019293/31db5c48-9a4c-4062-bbd0-8ca66d59fa33)

**Comment by 0atman** [comment]
ew, that is gross. thanks, will do. 

I use Privacy Badger to block most of these, great extension, afaik

**Comment by 0atman** [comment]
Replaced with static image. The only non-origin requests are now to the tailwind cdn (which I will also optimise, when I get round to it!)

Thank you very much!
