### ISSUE TITLE
Wrong short description when embedding the website.

### ISSUE THREAD

**Issue by Zyax3** [0atman/HumanMadeMark-com#4]
![Example](https://github.com/0atman/HumanMadeMark-com/assets/61208789/bbf336f6-52bd-4672-932c-a87388c87547)
It still says the website is about your podcast, not the Human Made Mark Project.

**Comment by 0atman** [comment]
That is very funny! Thank you so much for reporting - fixed in 3f91bac210e888b82fe97c8468d24e009ae41771
