### ISSUE TITLE
Textless Logo Files

### ISSUE THREAD

**Issue by IanOfGit** [0atman/HumanMadeMark-com#6]
Per our interaction in the YouTube comments for the announcement video: Please share files for a textless version of the logo that is just the head+plant glyph.

**Comment by 0atman** [comment]
It's a really good idea, thank you! thanks to generous time spent in #7 I'll publish this soon!

**Comment by royemosby** [comment]
The lurkers support you with imagery PRs

**Comment by 0atman** [comment]
Thank you so much for your time, Roy! I'll update the site ASAP, probably this weekend. 😊

**Comment by 0atman** [comment]
IT IS DONE! https://humanmademark.com/
Thank you so much @royemosby, and thank you, @IanOfGit, for making this issue! :smile:
