### ISSUE TITLE
add license?

### ISSUE THREAD

**Issue by suuppl** [0atman/HumanMadeMark-com#8]
Great project!

I'd be hesitant to use it, as there is no license in the project. (i think, maybe i just can't find it 😅) Maybe add a license.txt?

I am interpreting the readme as pretty much equivalent to CC0, but I think it would be better to clearly state your intent with an appropriate license.

You probably know the creative commons license picker, in case you need some inspiration ;)

thanks!

**Comment by 0atman** [comment]
Great idea! I've added the CC0 license :ok_hand:
